apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-aws-user-role
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "patch"]
  # Add permission to target pods in default namespace
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# Add permission for iptables and container runtime operations
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-aws-user-binding
subjects:
- kind: User
  name: "arn:aws:iam::724273188320:user/terasky_insight"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chaos-mesh-aws-user-role
  apiGroup: rbac.authorization.k8s.io 